- packages/ui/dist/components/VButton.js
- packages/ui/dist/components/VCheckbox.js
- packages/ui/dist/components/VForm.js
- packages/ui/dist/components/VInput.js
- packages/ui/dist/components/VList.js
- packages/ui/dist/components/VModal.js
- packages/ui/dist/components/VPageLoader.js
- packages/ui/dist/components/VPagination.js
- packages/ui/dist/components/VPassword.js
- packages/ui/dist/components/VRadio.js
- packages/ui/dist/components/VSelect.js
- packages/ui/dist/components/VSpinner.js
- packages/ui/dist/components/VTextarea.js
- packages/ui/dist/components/chunk-114c8aa6.js
- packages/ui/dist/components/chunk-373f7571.js
- packages/ui/dist/components/chunk-9b9bf453.js
- packages/ui/rollup.config.js
Связан с пр https://github.com/machinae/endpass-admin/pull/9
> chore(ui): change code-splitting build format

- packages/utils/__tests__/date.spec.js
- packages/utils/date.js
- packages/utils/nodejs
- packages/utils/package.json
> feat(utils): add fromTo, addToDate methods to date utils

- packages/class/package.json
- packages/class/src/CrossWindowBroadcaster.js
- packages/class/test/unit/specs/class/CrossWindowBroadcaster.spec.js
☝️ Needs to publish after merge.
> feat(class): makes send broadcase message public

- packages/class/package.json
- packages/class/src/transaction/TransactionFactory.js
Change crypto data pending trx factory
> Change crypto data pending trx factory

- packages/class/package.json
- packages/class/src/transaction/TransactionFactory.js
> Fix cryptodata timestamp

- packages/class/package.json
- packages/class/src/transaction/TransactionFactory.js
Cryptodata transaction network id
> Cryptodata transaction network id

- packages/e2e-utils/package.json
- packages/e2e-utils/rollup.config.js
> fix(e2e-utils): SW methods build name

- packages/ui/package.json
- packages/ui/src/kit/VDivider/VDivider.theme-default.scss
- packages/ui/src/kit/VDivider/VDivider.vue
- packages/ui/src/kit/VDivider/index.js
- packages/ui/src/scss/kit.theme-default.scss
- packages/ui/stories/VDivider.stories.js
- packages/ui/tests/unit/__snapshots__/storybook.spec.js.snap
> feat(ui): add v-divider component

- packages/ui/package.json
- packages/ui/src/kit/VContentSwitcher/VContentSwitcher.theme-default.scss
> feat(ui): improve VContentSwitcher variable item height

- packages/ui/package.json
- packages/ui/src/kit/VContentSwitcher/VContentSwitcher.theme-default.scss
> fix(ui): VContentSwitcher item height stretch

- packages/ui/package.json
- packages/ui/src/img/arrowLeft.svg
- packages/ui/src/img/close.svg
- packages/ui/src/kit/VModal/VModalCard/VModalCard.vue
- packages/ui/src/kit/VModal/VModalInfoCard/VModalInfoCard.theme-default.scss
- packages/ui/tests/unit/__snapshots__/storybook.spec.js.snap
> feat(ui): bundle VModalCard svg icons

- packages/ui/package.json
- packages/ui/src/kit/VModal/VModalCard/VModalCard.theme-default.scss
> style(ui): fix VModalCard box-sizing

- packages/ui/package.json
- packages/ui/src/kit/VModal/VModalCard/VModalCard.theme-default.scss
> style(ui): edit card title margin

- packages/ui/package.json
- packages/ui/src/kit/VCard/VCard.theme-default.scss
- packages/ui/src/kit/VCard/VCard.vue
- packages/ui/src/kit/VCard/VCardBody/VCardBody.theme-default.scss
- packages/ui/src/kit/VCard/VCardBody/VCardBody.vue
- packages/ui/src/kit/VCard/VCardBody/index.js
- packages/ui/src/kit/VCard/index.js
- packages/ui/src/scss/kit.theme-default.scss
- packages/ui/stories/VCard.stories.js
- packages/ui/tests/unit/__snapshots__/storybook.spec.js.snap
> feat(ui): add v-card component

- packages/ui/package.json
- packages/ui/src/atom/select-atom/select-atom.theme-default.scss
- packages/ui/src/kit/VSelect/VSelect.theme-default.scss
- packages/ui/src/kit/VSelect/VSelect.vue
- packages/ui/tests/unit/__snapshots__/storybook.spec.js.snap
> feat(ui): hide select system arrow

- packages/ui/package.json
- packages/ui/src/atom/select-atom/select-atom.theme-default.scss
- packages/ui/src/kit/VSelect/VSelect.theme-default.scss
- packages/ui/src/kit/VSelect/VSelect.vue
- packages/ui/tests/unit/__snapshots__/storybook.spec.js.snap
> fix(ui): v-select arrow background

- packages/eslint-plugin/package.json
- packages/eslint-plugin/yarn.lock
Update dependencies for eslint-plugin
> Update dependencies for eslint-plugin

- packages/utils/rollup.config.js
Update rollup config for utils
> Update rollup config for utils

- packages/ui/package.json
- packages/ui/src/atom/textarea-atom/textarea-atom.theme-default.scss
- packages/ui/src/atom/textarea-atom/textarea-atom.vue
- packages/ui/src/kit/VTextarea/VTextarea.vue
- packages/ui/src/kit/VTextarea/index.js
- packages/ui/src/scss/kit.theme-default.scss
- packages/ui/stories/VTextarea.stories.js
- packages/ui/tests/unit/__snapshots__/storybook.spec.js.snap
> feat(ui): v-textarea

- packages/ui/package.json
- packages/ui/src/atom/textarea-atom/textarea-atom.theme-default.scss
- packages/ui/src/kit/VTextarea/VTextarea.vue
- packages/ui/stories/VTextarea.stories.js
- packages/ui/tests/unit/__snapshots__/storybook.spec.js.snap
> feat(ui): add v-textarea skin

- packages/ui/package.json
- packages/ui/src/atom/textarea-atom/textarea-atom.theme-default.scss
- packages/ui/stories/VTextarea.stories.js
- packages/ui/tests/unit/__snapshots__/storybook.spec.js.snap
> feat(ui): add textarea atom explicit height

- packages/ui/package.json
- packages/ui/src/kit/VFileDropArea/VFileDropArea.vue
- packages/ui/src/kit/VProgressCircle/VProgressCircle.theme-default.scss
- packages/ui/src/kit/VProgressCircle/VProgressCircle.vue
- packages/ui/stories/VFileDropArea.stories.js
- packages/ui/stories/VProgressBar.stories.js
- packages/ui/tests/unit/__snapshots__/storybook.spec.js.snap
test(ui): add story for "accept case" for file loader
> feat(ui): add progress label to progress circle component

- packages/e2e-utils/package.json
- packages/e2e-utils/src/SWControllerDuplexBridge.js
BREAKING CHANGE: rename methods and change await finishSetup
> refactor(e2e-utils): change setup flow

- packages/class/package.json
- packages/class/src/error.js
> feat(class): add notification error group param

- packages/ui/package.json
- packages/ui/src/kit/VSelect/VSelect.vue
> fix(ui): v-select immutable listeners

- packages/ui/package.json
- packages/ui/src/atom/toggle-atom/toggle-atom.theme-default.scss
- packages/ui/src/atom/toggle-atom/toggle-atom.vue
- packages/ui/src/kit/VButton/VButton.vue
- packages/ui/src/kit/VToggle/VToggle.theme-default.scss
- packages/ui/src/kit/VToggle/VToggle.vue
- packages/ui/src/kit/VToggle/index.js
- packages/ui/src/scss/kit.theme-default.scss
- packages/ui/stories/VToggle.stories.js
- packages/ui/tests/unit/__snapshots__/storybook.spec.js.snap
> feat(ui): v-toggle

- packages/ui/package.json
- packages/ui/src/atom/toggle-atom/toggle-atom.theme-default.scss
- packages/ui/yarn.lock
> style(ui): v-toggle edit sizing

- packages/utils/package.json
- packages/utils/rollup.config.js
- packages/utils/src/asyncCheckProperty.js
- packages/utils/types/arrays.d.ts
- packages/utils/types/asyncCheckProperty.d.ts
- packages/utils/types/bipSeed.d.ts
- packages/utils/types/bs58.d.ts
- packages/utils/types/build.d.ts
- packages/utils/types/constants.d.ts
- packages/utils/types/crypto.d.ts
- packages/utils/types/date.d.ts
- packages/utils/types/generators.d.ts
- packages/utils/types/getOptionParameter.d.ts
- packages/utils/types/global.d.ts
- packages/utils/types/hex.d.ts
- packages/utils/types/isV3.d.ts
- packages/utils/types/keystoreCrypto.d.ts
- packages/utils/types/keystoreHDKeyVerify.d.ts
- packages/utils/types/keystoreHDSeedVerify.d.ts
- packages/utils/types/keystoreHDWallet.d.ts
- packages/utils/types/keystoreKeyGen.d.ts
- packages/utils/types/keystoreKeyVerify.d.ts
- packages/utils/types/keystoreWallet.d.ts
- packages/utils/types/mapToQueryString.d.ts
- packages/utils/types/numbers.d.ts
- packages/utils/types/objects.d.ts
- packages/utils/types/queryStringToMap.d.ts
- packages/utils/types/serviceWorkers.d.ts
- packages/utils/types/strings.d.ts
- packages/utils/types/walletGen.d.ts
Utils function in the `utils` package was undeclared in types declaration files, so we was forced to use `@ts-ignore` every time when wanted use one of utils. Did add declaration files for some of utils function.
> feat: add types declaration for certain utils in `utils` package

- packages/ui/package.json
- packages/ui/src/kit/VAccordion/VAccordionItem/VAccordionItem.theme-default.scss
- packages/ui/src/kit/VAccordion/VAccordionItem/VAccordionItem.vue
- packages/ui/tests/unit/__snapshots__/storybook.spec.js.snap
- Move classes of accordion item parts into the scope of accordion item
- Minor icon button appearance fix: remove outline in favor of highlighted item background
> fix(ui): move classes of accordion item into item's scope

- packages/ui/package.json
- packages/ui/src/kit/VAccordion/VAccordionItem/VAccordionItem.vue
- packages/ui/stories/VAccordion.stories.js
- packages/ui/tests/unit/__snapshots__/storybook.spec.js.snap
This feature will provide more flexible way to customize accordion items and replace them with custom ones. Closest use case can be viewed in the `vault`: adding new address functionality implemented through custom accordion item.
- Did add `hideIcon` property in the `VAccordionItem` component
> feat(ui): did add ability to hide accordion icon

- packages/ui/package.json
- packages/ui/src/kit/VAccordion/VAccordion.theme-default.scss
- packages/ui/src/kit/VAccordion/VAccordion.vue
- packages/ui/src/kit/VAccordion/VAccordionItem/VAccordionItem.theme-default.scss
- packages/ui/stories/VAccordion.stories.js
- packages/ui/tests/unit/__snapshots__/storybook.spec.js.snap
Did add support for `small` and `normal` accordion sizes. Also did refactor styles, remove nesting.
> E-106: feat(ui): accordion sizes

- packages/ui/package.json
- packages/ui/src/kit/VTab/VTab.vue
- packages/ui/src/kit/VTabs/VTabContent.vue
- packages/ui/src/kit/VTabs/VTabs.vue
- packages/ui/stories/VTabs.stories.js
- packages/ui/tests/unit/__snapshots__/storybook.spec.js.snap
BREAKING CHANGE: VTab component now requires id property
> fix(ui): make VTabs component reactive

- packages/ui/package.json
- packages/ui/src/kit/VInputGroup/VInputGroup.theme-default.scss
- packages/ui/src/kit/VInputGroup/VInputGroup.vue
- packages/ui/src/kit/VInputGroup/index.js
- packages/ui/src/kit/index.js
- packages/ui/src/scss/kit.theme-default.scss
- packages/ui/stories/VInputGroup.stories.js
- packages/ui/tests/unit/__snapshots__/storybook.spec.js.snap
This component will group inputs between themselves, remove border radius and add border between grouped inputs.
> E-416 feat: input group component

- packages/ui/package.json
- packages/ui/src/kit/VRadio/VRadio.theme-default.scss
- packages/ui/src/kit/VRadio/VRadio.vue
- packages/ui/src/molecule/label-molecule/label-molecule.theme-default.scss
- packages/ui/src/molecule/label-molecule/label-molecule.vue
- packages/ui/src/molecule/tooltip-molecule/tooltip-molecule.theme-default.scss
- packages/ui/src/molecule/tooltip-molecule/tooltip-molecule.vue
- packages/ui/src/scss/kit.theme-default.scss
- packages/ui/stories/VRadio.stories.js
- packages/ui/tests/unit/__snapshots__/storybook.spec.js.snap
Did add tooltips for `VRadio` component. Also did fix incorrect offset of radio inputs in Vault.
> E-787 feat: add tooltips for radio

- packages/ui/package.json
- packages/ui/src/atom/circular-loader-atom/circular-loader-atom.theme-default.scss
- packages/ui/src/atom/circular-loader-atom/circular-loader-atom.vue
- packages/ui/src/kit/VCircularLoader/VCircularLoader.vue
- packages/ui/src/kit/VCircularLoader/index.js
- packages/ui/src/kit/VProgressCircle/VProgressCircle.theme-default.scss
- packages/ui/src/kit/VProgressCircle/VProgressCircle.vue
- packages/ui/src/kit/index.js
- packages/ui/src/scss/kit.theme-default.scss
- packages/ui/stories/VCircularLoader.stories.js
- packages/ui/stories/VProgressCircle.stories.js
- packages/ui/tests/unit/__snapshots__/storybook.spec.js.snap
> feat: customizible progress circle
